repos:
  - repo: local
    hooks:
      - id: run-tests
        name: Run tests
        entry: poetry run pytest src
        language: system
        pass_filenames: false
        always_run: true
      - id: coverage-image
        name: Update coverage image
        entry: poetry run invoke coverage-image
        language: system
        pass_filenames: false
        always_run: true
